name: Build
on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: full

    steps:
      - uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          default: true
          override: true

      - name: Build and test
        timeout-minutes: 20
        run: |
          cargo build
      
      - uses: actions/upload-artifact@v3
        with:
          name: bim-linux
          path: |
            target/debug/bim
  
  build-windows:
    runs-on: windows-latest
    env:
      RUST_BACKTRACE: full

    steps:
      - uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          default: true
          override: true

      - name: Build
        timeout-minutes: 20
        run: |
          cargo build
      
      - uses: actions/upload-artifact@v3
        with:
          name: bim-windows
          path: |
            target/debug/bim.exe
  
  build-macos:
    runs-on: macos-latest
    env:
      RUST_BACKTRACE: full

    steps:
      - uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          default: true
          override: true

      - name: Build
        timeout-minutes: 20
        run: |
          cargo build
      
      - uses: actions/upload-artifact@v3
        with:
          name: bim-macos
          path: |
            target/debug/bim
