name: Build Releases
on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  build-cross:
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: full
    
    strategy:
      matrix:
        target:
          - i586-unknown-linux-musl
          - x86_64-unknown-linux-musl
          - armv7-unknown-linux-musleabi
          - aarch64-unknown-linux-musl
          - mipsel-unknown-linux-musl
          - mips64el-unknown-linux-muslabi64

    steps:
      - uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          target: ${{ matrix.target }}
          toolchain: nightly
          default: true
          override: true

      - name: Install cross
        run: cargo install cross

      - name: Build ${{ matrix.target }}
        timeout-minutes: 120
        run: |
          cross build --target ${{ matrix.target }} -r
          ls -lR
