name: Build Releases
on:
  push:
    tags:
      - v*

env:
  CARGO_TERM_COLOR: always

jobs:
  build-cross:
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: full
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          target: ${{ matrix.target }}
          toolchain: nightly
          default: true
          override: true

      - name: Install cross
        run: cargo install cross

      - name: Build ${{ matrix.target }}
        timeout-minutes: 120
        run: |
          sudo apt install -y libssl-dev
          cross build --target x86_64-unknown-linux-musl --release
          mv target/x86_64-unknown-linux-musl/release/bim build/release/bim-${{ github.ref_name }}-x86_64
          mkdir -p build/release

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3.1.0
        with:
          path: build/release/*
