name: Build

on:
  push:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

jobs:
  build-linux:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-musl

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          target: ${{ matrix.target }}

      - name: Install cross
        run: cargo install cross

      - name: Build ${{ matrix.target }}
        timeout-minutes: 15
        run: |
          mkdir -p build/release
          cross build --target ${{ matrix.target }} --release
          cp target/${{ matrix.target }}/release/bim build/release/bim
      
      - name: UPX Compress
        uses: crazy-max/ghaction-upx@v2
        with:
          version: latest
          files: |
            build/release/bim
          args: --best --lzma
    
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bim-${{ matrix.target }}
          path: build/release/*

  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly

      - name: Build
        timeout-minutes: 15
        run: |
          cargo build --release
          mkdir build\release
          copy target\release\bim.exe build\release\bim.exe

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bim-windows
          path: build/release/*

  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly

      - name: Build
        timeout-minutes: 15
        run: |
          cargo build --release
          mkdir -p build/release
          cp target/release/bim build/release/bim

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bim-macos
          path: build/release/*
