name: Build Releases
on:
  push:
    tags:
      - v*

env:
  CARGO_TERM_COLOR: always

jobs:
  build-cross:
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: full
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          target: ${{ matrix.target }}
          toolchain: nightly
          default: true
          override: true

      - name: Build ${{ matrix.target }}
        timeout-minutes: 120
        run: |
          cargo build -r
          mkdir -p build/release
          mv bim build/release/bim-${{ github.ref_name }}-x86_64

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3.1.0
        with:
          path: build/release/*
